spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/gamebook;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

server:
  servlet:
    session:
      tracking-modes: cookie

logging:
  level:
    org.hibernate.SQL: debug